# A __main__.py generated by python-boilerplate.  For now, not using it.
# Eventually, it can be used to facilitate CLI usage of the package, e.g.
# $ python xrb <args...>
# It remains to be seen if this is something we'll want/need.  Leaving this for
# now.

import argparse
import xrb
from xrb import __version__


def get_parser():
    """
    Creates a new argument parser.
    """
    parser = argparse.ArgumentParser('xrb')
    version = '%(prog)s ' + __version__
    parser.add_argument('--version', '-v', action='version', version=version)
    return parser

def main(args=None):
    """
    Main entry point for your project.

    Args:
        args : list
            A of arguments as if they were input in the command line. Leave it
            None to use sys.argv.
    """

    parser = get_parser()
    args = parser.parse_args(args)

    # Put your main script logic here
    print('No action defined for xrb module!')


if __name__ == '__main__':
    main()
